if(NOT STRING_INDENTATION)
    set(STRING_INDENTATION 50)
endif()

function(indent_string STR LEN)
    string(LENGTH ${STR} CURLEN)
    while(${CURLEN} LESS ${LEN})
        set(STR "${STR} ")
        string(LENGTH ${STR} CURLEN)
    endwhile()
    set(MSG ${STR} PARENT_SCOPE)
endfunction()

function(display_message)
    if(${ARGC} GREATER 0)
        set(MSG "${ARGV0}")
        if(${ARGC} GREATER 1)
            indent_string(${MSG} ${STRING_INDENTATION})

            set(CUR_ARGC 1)
            while(${CUR_ARGC} LESS ${ARGC})
                if(${CUR_ARGC} GREATER 1)
                    set(MSG "${MSG};")
                endif()
                set(MSG "${MSG}${ARGV${CUR_ARGC}}")
                math(EXPR CUR_ARGC "${CUR_ARGC} + 1")
            endwhile()
        endif()
        message(STATUS "${MSG}")
        unset(MSG)
    else()
        message(STATUS "")
    endif()
endfunction()

function(display_variable VARIABLE_NAME)
    if(DEFINED ${VARIABLE_NAME})
        display_message(${VARIABLE_NAME} ${${VARIABLE_NAME}})
    else()
        display_message(${VARIABLE_NAME} "Not defined")
    endif()
endfunction()

function(display_separator)
    math(EXPR TMP_INDENT "${STRING_INDENTATION} / 2")
    set(MSG "#")
    string(LENGTH ${MSG} CURLEN)
    while(${CURLEN} LESS ${TMP_INDENT})
        set(MSG "${MSG}#")
        string(LENGTH ${MSG} CURLEN)
    endwhile()

    if(${ARGC} GREATER 0)
        set(MSG "${MSG} ${ARGV0} ")
    endif()

    math(EXPR TMP_INDENT "${STRING_INDENTATION} * 2")
    string(LENGTH ${MSG} CURLEN)
    while(${CURLEN} LESS ${TMP_INDENT})
        set(MSG "${MSG}#")
        string(LENGTH ${MSG} CURLEN)
    endwhile()
    message(STATUS "${MSG}")
endfunction()

function(display_subseparator)
    set(MSG "###")
    if(${ARGC} GREATER 0)
        set(MSG "${MSG} ${ARGV0} ")
    endif()
    message(STATUS "${MSG}")
endfunction()

function(display_header header_string)
    display_separator(${header_string})
endfunction()
